// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/yusing/gotify-api-client/v2/client/application"
	clientops "github.com/yusing/gotify-api-client/v2/client/client"
	"github.com/yusing/gotify-api-client/v2/client/health"
	"github.com/yusing/gotify-api-client/v2/client/message"
	"github.com/yusing/gotify-api-client/v2/client/plugin"
	"github.com/yusing/gotify-api-client/v2/client/user"
	"github.com/yusing/gotify-api-client/v2/client/version"
)

// Default gotify REST API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http", "https"}

// NewHTTPClient creates a new gotify REST API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *GotifyRESTAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new gotify REST API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *GotifyRESTAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new gotify REST API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *GotifyRESTAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(GotifyRESTAPI)
	cli.Transport = transport
	cli.Application = application.New(transport, formats)
	cli.Client = clientops.New(transport, formats)
	cli.Health = health.New(transport, formats)
	cli.Message = message.New(transport, formats)
	cli.Plugin = plugin.New(transport, formats)
	cli.User = user.New(transport, formats)
	cli.Version = version.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// GotifyRESTAPI is a client for gotify REST API
type GotifyRESTAPI struct {
	Application application.ClientService

	Client clientops.ClientService

	Health health.ClientService

	Message message.ClientService

	Plugin plugin.ClientService

	User user.ClientService

	Version version.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *GotifyRESTAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Application.SetTransport(transport)
	c.Client.SetTransport(transport)
	c.Health.SetTransport(transport)
	c.Message.SetTransport(transport)
	c.Plugin.SetTransport(transport)
	c.User.SetTransport(transport)
	c.Version.SetTransport(transport)
}
