// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetMessagesParams creates a new GetMessagesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMessagesParams() *GetMessagesParams {
	return &GetMessagesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMessagesParamsWithTimeout creates a new GetMessagesParams object
// with the ability to set a timeout on a request.
func NewGetMessagesParamsWithTimeout(timeout time.Duration) *GetMessagesParams {
	return &GetMessagesParams{
		timeout: timeout,
	}
}

// NewGetMessagesParamsWithContext creates a new GetMessagesParams object
// with the ability to set a context for a request.
func NewGetMessagesParamsWithContext(ctx context.Context) *GetMessagesParams {
	return &GetMessagesParams{
		Context: ctx,
	}
}

// NewGetMessagesParamsWithHTTPClient creates a new GetMessagesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMessagesParamsWithHTTPClient(client *http.Client) *GetMessagesParams {
	return &GetMessagesParams{
		HTTPClient: client,
	}
}

/*
GetMessagesParams contains all the parameters to send to the API endpoint

	for the get messages operation.

	Typically these are written to a http.Request.
*/
type GetMessagesParams struct {

	/* Limit.

	   the maximal amount of messages to return

	   Default: 100
	*/
	Limit *int64

	/* Since.

	   return all messages with an ID less than this value

	   Format: int64
	*/
	Since *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get messages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMessagesParams) WithDefaults() *GetMessagesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get messages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMessagesParams) SetDefaults() {
	var (
		limitDefault = int64(100)
	)

	val := GetMessagesParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get messages params
func (o *GetMessagesParams) WithTimeout(timeout time.Duration) *GetMessagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get messages params
func (o *GetMessagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get messages params
func (o *GetMessagesParams) WithContext(ctx context.Context) *GetMessagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get messages params
func (o *GetMessagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get messages params
func (o *GetMessagesParams) WithHTTPClient(client *http.Client) *GetMessagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get messages params
func (o *GetMessagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get messages params
func (o *GetMessagesParams) WithLimit(limit *int64) *GetMessagesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get messages params
func (o *GetMessagesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithSince adds the since to the get messages params
func (o *GetMessagesParams) WithSince(since *int64) *GetMessagesParams {
	o.SetSince(since)
	return o
}

// SetSince adds the since to the get messages params
func (o *GetMessagesParams) SetSince(since *int64) {
	o.Since = since
}

// WriteToRequest writes these params to a swagger request
func (o *GetMessagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Since != nil {

		// query param since
		var qrSince int64

		if o.Since != nil {
			qrSince = *o.Since
		}
		qSince := swag.FormatInt64(qrSince)
		if qSince != "" {

			if err := r.SetQueryParam("since", qSince); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
