// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/yusing/gotify-api-client/v2/models"
)

// CreateAppReader is a Reader for the CreateApp structure.
type CreateAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateAppBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewCreateAppUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateAppForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /application] createApp", response, response.Code())
	}
}

// NewCreateAppOK creates a CreateAppOK with default headers values
func NewCreateAppOK() *CreateAppOK {
	return &CreateAppOK{}
}

/*
CreateAppOK describes a response with status code 200, with default header values.

Ok
*/
type CreateAppOK struct {
	Payload *models.Application
}

// IsSuccess returns true when this create app o k response has a 2xx status code
func (o *CreateAppOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create app o k response has a 3xx status code
func (o *CreateAppOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create app o k response has a 4xx status code
func (o *CreateAppOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create app o k response has a 5xx status code
func (o *CreateAppOK) IsServerError() bool {
	return false
}

// IsCode returns true when this create app o k response a status code equal to that given
func (o *CreateAppOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create app o k response
func (o *CreateAppOK) Code() int {
	return 200
}

func (o *CreateAppOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /application][%d] createAppOK %s", 200, payload)
}

func (o *CreateAppOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /application][%d] createAppOK %s", 200, payload)
}

func (o *CreateAppOK) GetPayload() *models.Application {
	return o.Payload
}

func (o *CreateAppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Application)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAppBadRequest creates a CreateAppBadRequest with default headers values
func NewCreateAppBadRequest() *CreateAppBadRequest {
	return &CreateAppBadRequest{}
}

/*
CreateAppBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateAppBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this create app bad request response has a 2xx status code
func (o *CreateAppBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create app bad request response has a 3xx status code
func (o *CreateAppBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create app bad request response has a 4xx status code
func (o *CreateAppBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create app bad request response has a 5xx status code
func (o *CreateAppBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create app bad request response a status code equal to that given
func (o *CreateAppBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create app bad request response
func (o *CreateAppBadRequest) Code() int {
	return 400
}

func (o *CreateAppBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /application][%d] createAppBadRequest %s", 400, payload)
}

func (o *CreateAppBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /application][%d] createAppBadRequest %s", 400, payload)
}

func (o *CreateAppBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateAppBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAppUnauthorized creates a CreateAppUnauthorized with default headers values
func NewCreateAppUnauthorized() *CreateAppUnauthorized {
	return &CreateAppUnauthorized{}
}

/*
CreateAppUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type CreateAppUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this create app unauthorized response has a 2xx status code
func (o *CreateAppUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create app unauthorized response has a 3xx status code
func (o *CreateAppUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create app unauthorized response has a 4xx status code
func (o *CreateAppUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this create app unauthorized response has a 5xx status code
func (o *CreateAppUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this create app unauthorized response a status code equal to that given
func (o *CreateAppUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the create app unauthorized response
func (o *CreateAppUnauthorized) Code() int {
	return 401
}

func (o *CreateAppUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /application][%d] createAppUnauthorized %s", 401, payload)
}

func (o *CreateAppUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /application][%d] createAppUnauthorized %s", 401, payload)
}

func (o *CreateAppUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateAppUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateAppForbidden creates a CreateAppForbidden with default headers values
func NewCreateAppForbidden() *CreateAppForbidden {
	return &CreateAppForbidden{}
}

/*
CreateAppForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateAppForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this create app forbidden response has a 2xx status code
func (o *CreateAppForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create app forbidden response has a 3xx status code
func (o *CreateAppForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create app forbidden response has a 4xx status code
func (o *CreateAppForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create app forbidden response has a 5xx status code
func (o *CreateAppForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create app forbidden response a status code equal to that given
func (o *CreateAppForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create app forbidden response
func (o *CreateAppForbidden) Code() int {
	return 403
}

func (o *CreateAppForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /application][%d] createAppForbidden %s", 403, payload)
}

func (o *CreateAppForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /application][%d] createAppForbidden %s", 403, payload)
}

func (o *CreateAppForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateAppForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
