// Code generated by go-swagger; DO NOT EDIT.

package application

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewRemoveAppImageParams creates a new RemoveAppImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewRemoveAppImageParams() *RemoveAppImageParams {
	return &RemoveAppImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveAppImageParamsWithTimeout creates a new RemoveAppImageParams object
// with the ability to set a timeout on a request.
func NewRemoveAppImageParamsWithTimeout(timeout time.Duration) *RemoveAppImageParams {
	return &RemoveAppImageParams{
		timeout: timeout,
	}
}

// NewRemoveAppImageParamsWithContext creates a new RemoveAppImageParams object
// with the ability to set a context for a request.
func NewRemoveAppImageParamsWithContext(ctx context.Context) *RemoveAppImageParams {
	return &RemoveAppImageParams{
		Context: ctx,
	}
}

// NewRemoveAppImageParamsWithHTTPClient creates a new RemoveAppImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewRemoveAppImageParamsWithHTTPClient(client *http.Client) *RemoveAppImageParams {
	return &RemoveAppImageParams{
		HTTPClient: client,
	}
}

/*
RemoveAppImageParams contains all the parameters to send to the API endpoint

	for the remove app image operation.

	Typically these are written to a http.Request.
*/
type RemoveAppImageParams struct {

	/* ID.

	   the application id

	   Format: int64
	*/
	ID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the remove app image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveAppImageParams) WithDefaults() *RemoveAppImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the remove app image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *RemoveAppImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the remove app image params
func (o *RemoveAppImageParams) WithTimeout(timeout time.Duration) *RemoveAppImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove app image params
func (o *RemoveAppImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove app image params
func (o *RemoveAppImageParams) WithContext(ctx context.Context) *RemoveAppImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove app image params
func (o *RemoveAppImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove app image params
func (o *RemoveAppImageParams) WithHTTPClient(client *http.Client) *RemoveAppImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove app image params
func (o *RemoveAppImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the remove app image params
func (o *RemoveAppImageParams) WithID(id int64) *RemoveAppImageParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the remove app image params
func (o *RemoveAppImageParams) SetID(id int64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveAppImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
